# Generated by Django 4.0.1 on 2022-01-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mconfig',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
