# Generated by Django 4.0.1 on 2022-01-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_mconfig_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mconfig',
            name='Packet',
        ),
        migrations.AddField(
            model_name='mconfig',
            name='Packet',
            field=models.ManyToManyField(to='inventory.PType'),
        ),
    ]
