# Generated by Django 4.0.1 on 2022-01-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_customer_units_remove_mconfig_packet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
