# Generated by Django 4.0.1 on 2022-01-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_ptype_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mconfig',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
